version: 2

updates:
  # Terraform - One entry per thing we want to scan as per https://github.com/dependabot/dependabot-core/issues/649
  - package-ecosystem: "terraform" # DNS
    directory: "/bestow-code/core_analysis/repository"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # GKE Dev
    directory: "/gke/dev"
    schedule:
      interval: "weekly"
