name: Terraform CI

on:
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
